// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 HexxLock

package declarative

import (
	"strings"
	"testing"

	keystonev1alpha1 "github.com/dogukanturhal/keystone/api/v1alpha1"
	"github.com/dogukanturhal/keystone-sdk/go/drift"
)

// Regression cover for three defects that all shared one root cause: the
// snapshot recorded a column's type family but not its modifiers, and did not
// record identity at all.
//
// Observed against a real 50-table schema (2026-07-26): a diff from an empty
// baseline turned ten GENERATED BY DEFAULT AS IDENTITY columns into plain
// NOT NULL columns and widened every varchar(n) to unbounded varchar. The
// migration applied cleanly and every subsequent insert failed with
// 23502 null value in column "id" — the worst possible place for it to
// surface, since apply-time looked healthy.

func TestRenderColumnDefEmitsIdentity(t *testing.T) {
	cases := []struct {
		name     string
		identity string
		want     string
	}{
		{"by default", "BY DEFAULT", "GENERATED BY DEFAULT AS IDENTITY"},
		{"always", "ALWAYS", "GENERATED ALWAYS AS IDENTITY"},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := renderColumnDef(keystonev1alpha1.DesiredColumn{
				Name:     "id",
				Type:     "smallint",
				Identity: tc.identity,
			})
			if !strings.Contains(got, tc.want) {
				t.Fatalf("renderColumnDef() = %q, want it to contain %q", got, tc.want)
			}
		})
	}
}

func TestRenderColumnDefOmitsIdentityWhenUnset(t *testing.T) {
	got := renderColumnDef(keystonev1alpha1.DesiredColumn{Name: "slug", Type: "text"})
	if strings.Contains(got, "IDENTITY") {
		t.Fatalf("renderColumnDef() = %q, want no IDENTITY clause", got)
	}
}

// Identity must precede PRIMARY KEY: PostgreSQL accepts either order, but
// matching pg_dump's ordering keeps hand-diffing a migration against a dump
// readable.
func TestRenderColumnDefOrdersIdentityBeforePrimaryKey(t *testing.T) {
	got := renderColumnDef(keystonev1alpha1.DesiredColumn{
		Name:       "id",
		Type:       "bigint",
		Identity:   "BY DEFAULT",
		PrimaryKey: true,
	})

	idIdx := strings.Index(got, "IDENTITY")
	pkIdx := strings.Index(got, "PRIMARY KEY")
	if idIdx < 0 || pkIdx < 0 || idIdx > pkIdx {
		t.Fatalf("renderColumnDef() = %q, want IDENTITY before PRIMARY KEY", got)
	}
}

// ResolveColumnTypeShape must prefer format_type output, which carries length,
// numeric precision and PostGIS typmod. Falling back to data_type silently
// drops all three.
func TestResolveColumnTypeShapePreservesModifiers(t *testing.T) {
	cases := []struct {
		name  string
		shape drift.ColumnShape
		want  string
	}{
		{
			name:  "varchar keeps its length",
			shape: drift.ColumnShape{DataType: "character varying", UDTName: "varchar", FormattedType: "character varying(64)"},
			want:  "character varying(64)",
		},
		{
			name:  "numeric keeps precision and scale",
			shape: drift.ColumnShape{DataType: "numeric", UDTName: "numeric", FormattedType: "numeric(20,2)"},
			want:  "numeric(20,2)",
		},
		{
			name:  "postgis geography keeps type and SRID",
			shape: drift.ColumnShape{DataType: "USER-DEFINED", UDTName: "geography", FormattedType: "geography(Point,4326)"},
			want:  "geography(Point,4326)",
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := drift.ResolveColumnTypeShape(tc.shape); got != tc.want {
				t.Fatalf("ResolveColumnTypeShape() = %q, want %q", got, tc.want)
			}
		})
	}
}

// Snapshots taken before FormattedType existed must still resolve, or an
// upgrade would read every stored snapshot as total drift.
func TestResolveColumnTypeShapeFallsBackForOlderSnapshots(t *testing.T) {
	cases := []struct {
		shape drift.ColumnShape
		want  string
	}{
		{drift.ColumnShape{DataType: "ARRAY", UDTName: "_text"}, "text[]"},
		{drift.ColumnShape{DataType: "USER-DEFINED", UDTName: "record_kind"}, "record_kind"},
		{drift.ColumnShape{DataType: "timestamp with time zone", UDTName: "timestamptz"}, "timestamp with time zone"},
	}

	for _, tc := range cases {
		if got := drift.ResolveColumnTypeShape(tc.shape); got != tc.want {
			t.Fatalf("ResolveColumnTypeShape(%+v) = %q, want %q", tc.shape, got, tc.want)
		}
	}
}

func TestIdentityClause(t *testing.T) {
	cases := map[string]string{
		"a": "GENERATED ALWAYS AS IDENTITY",
		"d": "GENERATED BY DEFAULT AS IDENTITY",
		"":  "",
		"x": "",
	}

	for attidentity, want := range cases {
		if got := drift.IdentityClause(attidentity); got != want {
			t.Fatalf("IdentityClause(%q) = %q, want %q", attidentity, got, want)
		}
	}
}

// The scratch schema the differ normalises a sql:// desired source into is
// content-hash named, so format_type qualifies user-defined types with a name
// that differs between the two sides of every diff. Left unstripped, every
// enum column reports type drift on every run and none of it is real.
func TestResolveColumnTypeShapeStripsScratchSchemaQualifier(t *testing.T) {
	cases := []struct {
		name  string
		shape drift.ColumnShape
		want  string
	}{
		{
			name:  "enum qualified by a scratch schema",
			shape: drift.ColumnShape{DataType: "USER-DEFINED", UDTName: "record_kind", FormattedType: "keystone_dev_2c3a8f55f325.record_kind"},
			want:  "record_kind",
		},
		{
			name:  "postgis type keeps its modifiers after stripping",
			shape: drift.ColumnShape{DataType: "USER-DEFINED", UDTName: "geography", FormattedType: "gis.geography(Point,4326)"},
			want:  "geography(Point,4326)",
		},
		{
			name:  "unqualified is untouched",
			shape: drift.ColumnShape{DataType: "numeric", UDTName: "numeric", FormattedType: "numeric(20,2)"},
			want:  "numeric(20,2)",
		},
		{
			name:  "qualifier that is not the type's own name is left alone",
			shape: drift.ColumnShape{DataType: "USER-DEFINED", UDTName: "record_kind", FormattedType: "other.something_else"},
			want:  "other.something_else",
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := drift.ResolveColumnTypeShape(tc.shape); got != tc.want {
				t.Fatalf("ResolveColumnTypeShape() = %q, want %q", got, tc.want)
			}
		})
	}
}

// Extensions must be emitted before every other object: a column cannot be
// declared with a type the extension has not yet created. Without this the
// authored migration is valid only against a database where someone already
// ran CREATE EXTENSION by hand, and fails on a fresh one with
// 42704 type "citext" does not exist.
func TestDiffEmitsExtensionsBeforeTables(t *testing.T) {
	observed := &drift.Snapshot{Schema: "public"}
	desired := &keystonev1alpha1.SchemaDefinitionSpec{
		Extensions: []keystonev1alpha1.DesiredExtension{{Name: "citext"}},
		Tables: []keystonev1alpha1.DesiredTable{{
			Name: "accounts",
			Columns: []keystonev1alpha1.DesiredColumn{
				{Name: "email", Type: "citext"},
			},
		}},
	}

	plan, err := Diff(observed, desired)
	if err != nil {
		t.Fatalf("Diff() error = %v", err)
	}

	extIdx, tblIdx := -1, -1
	for i, stmt := range plan.Statements {
		if extIdx < 0 && strings.Contains(stmt, "CREATE EXTENSION") {
			extIdx = i
		}
		if tblIdx < 0 && strings.Contains(stmt, "CREATE TABLE") {
			tblIdx = i
		}
	}

	if extIdx < 0 {
		t.Fatalf("no CREATE EXTENSION emitted; statements = %v", plan.Statements)
	}
	if tblIdx >= 0 && extIdx > tblIdx {
		t.Fatalf("CREATE EXTENSION at %d must precede CREATE TABLE at %d", extIdx, tblIdx)
	}
}

// An extension already installed must not be re-emitted, or every diff churns.
func TestDiffSkipsInstalledExtensions(t *testing.T) {
	observed := &drift.Snapshot{
		Schema:     "public",
		Extensions: []drift.ExtShape{{Name: "citext"}},
	}
	desired := &keystonev1alpha1.SchemaDefinitionSpec{
		Extensions: []keystonev1alpha1.DesiredExtension{{Name: "citext"}},
	}

	plan, err := Diff(observed, desired)
	if err != nil {
		t.Fatalf("Diff() error = %v", err)
	}

	for _, stmt := range plan.Statements {
		if strings.Contains(stmt, "CREATE EXTENSION") {
			t.Fatalf("re-emitted CREATE EXTENSION for an installed extension: %q", stmt)
		}
	}
}

// Dropping an extension is never authored: extensions are database-scoped and
// routinely shared, so removing one because a single schema stopped
// referencing it would break tenants the differ cannot see.
func TestDiffNeverDropsExtensions(t *testing.T) {
	observed := &drift.Snapshot{
		Schema:     "public",
		Extensions: []drift.ExtShape{{Name: "postgis"}},
	}
	desired := &keystonev1alpha1.SchemaDefinitionSpec{}

	plan, err := Diff(observed, desired)
	if err != nil {
		t.Fatalf("Diff() error = %v", err)
	}

	for _, stmt := range plan.Statements {
		if strings.Contains(strings.ToUpper(stmt), "DROP EXTENSION") {
			t.Fatalf("authored a DROP EXTENSION: %q", stmt)
		}
	}
}

// A generated column carries its expression in generation_expression, never in
// column_default. A renderer that emits only the default produces a column that
// exists, accepts no writes, and reads as NULL forever — so a derived value such
// as a PostGIS point built from a coordinate pair silently stops existing.
func TestRenderColumnDefEmitsGeneratedStored(t *testing.T) {
	got := renderColumnDef(keystonev1alpha1.DesiredColumn{
		Name:      "name_en",
		Type:      "text",
		Nullable:  true,
		Generated: "name ->> 'en'",
	})

	if !strings.Contains(got, "GENERATED ALWAYS AS (name ->> 'en') STORED") {
		t.Fatalf("renderColumnDef() = %q, want a GENERATED ... STORED clause", got)
	}
}

// PostgreSQL rejects a column declaring both, and the expression is the column's
// only source of value.
func TestRenderColumnDefSuppressesDefaultOnGeneratedColumn(t *testing.T) {
	got := renderColumnDef(keystonev1alpha1.DesiredColumn{
		Name:      "computed",
		Type:      "integer",
		Nullable:  true,
		Default:   "0",
		Generated: "1 + 1",
	})

	if strings.Contains(got, "DEFAULT") {
		t.Fatalf("renderColumnDef() = %q, want no DEFAULT alongside GENERATED", got)
	}
}

// The generated clause belongs immediately after the type, as pg_dump writes it.
func TestRenderColumnDefOrdersGeneratedBeforeNotNull(t *testing.T) {
	got := renderColumnDef(keystonev1alpha1.DesiredColumn{
		Name:      "total",
		Type:      "integer",
		Nullable:  false,
		Generated: "a + b",
	})

	genIdx := strings.Index(got, "GENERATED")
	nnIdx := strings.Index(got, "NOT NULL")
	if genIdx < 0 || nnIdx < 0 || genIdx > nnIdx {
		t.Fatalf("renderColumnDef() = %q, want GENERATED before NOT NULL", got)
	}
}
