// SPDX-License-Identifier: Apache-2.0

//go:build integration

// Integration tests for the dev-database normaliser. Runs against the
// shared dev database (internal/testdb: KEYSTONE_TEST_DSN, else a
// testcontainer). Run with:
//
//	go test -count=1 -tags integration ./schemasource/
package schemasource

import (
	"context"
	"fmt"
	"testing"

	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/dogukanturhal/keystone-sdk/go/drift"
	"github.com/dogukanturhal/keystone-sdk/go/internal/testdb"
	"github.com/dogukanturhal/keystone-sdk/go/schemaspec"
)

// devPool returns the shared dev database. Resolution lives in
// internal/testdb so every integration suite in this module gets a
// database the same way — including from an already-running server named
// by KEYSTONE_TEST_DSN, which is what lets this suite run in CI.
func devPool(t *testing.T) *pgxpool.Pool {
	t.Helper()
	return testdb.Pool(t)
}

func TestSnapshotFromDDL(t *testing.T) {
	ctx := context.Background()
	pool := devPool(t)

	ddl := `
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL
);
CREATE UNIQUE INDEX idx_users_email ON users (email);
`
	snap, err := SnapshotFromDDL(ctx, pool, ddl, "public")
	if err != nil {
		t.Fatalf("SnapshotFromDDL: %v", err)
	}
	if len(snap.Tables) != 1 || snap.Tables[0].Name != "users" {
		t.Fatalf("expected users table, got %+v", snap.Tables)
	}
	if len(snap.Tables[0].Columns) != 2 {
		t.Errorf("expected 2 columns, got %d", len(snap.Tables[0].Columns))
	}
	// And it converts cleanly to a desired spec.
	spec := schemaspec.FromSnapshot(snap, schemaspec.Options{SchemaRef: "app"})
	if len(spec.Tables) != 1 {
		t.Errorf("FromSnapshot: expected 1 table, got %d", len(spec.Tables))
	}
}

func TestSnapshotFromDDL_DropsScratchSchema(t *testing.T) {
	ctx := context.Background()
	pool := devPool(t)

	if _, err := SnapshotFromDDL(ctx, pool, "CREATE TABLE t (id bigint);", "public"); err != nil {
		t.Fatalf("SnapshotFromDDL: %v", err)
	}
	// No keystone_dev_* schema should survive.
	var n int
	err := pool.QueryRow(ctx,
		`SELECT count(*) FROM information_schema.schemata WHERE schema_name LIKE 'keystone_dev_%'`).Scan(&n)
	if err != nil {
		t.Fatal(err)
	}
	if n != 0 {
		t.Errorf("scratch schema not cleaned up: %d remain", n)
	}
}

func TestSnapshotFromFiles_Replay(t *testing.T) {
	ctx := context.Background()
	pool := devPool(t)

	// Two ordered migrations: create then alter. Replaying both yields the
	// cumulative final state.
	files := map[string]string{
		"001_create.up.sql":  "SET LOCAL statement_timeout = '30s';\nCREATE TABLE widgets (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);",
		"002_add_col.up.sql": "SET LOCAL statement_timeout = '30s';\nALTER TABLE widgets ADD COLUMN name TEXT NOT NULL DEFAULT '';",
	}
	snap, err := SnapshotFromFiles(ctx, pool, files, "public")
	if err != nil {
		t.Fatalf("SnapshotFromFiles: %v", err)
	}
	if len(snap.Tables) != 1 || snap.Tables[0].Name != "widgets" {
		t.Fatalf("expected widgets table, got %+v", snap.Tables)
	}
	if len(snap.Tables[0].Columns) != 2 {
		t.Errorf("replay did not apply the ALTER (expected 2 columns), got %d", len(snap.Tables[0].Columns))
	}
}

func TestResolveDesired_DB(t *testing.T) {
	ctx := context.Background()
	pool := devPool(t)

	// Seed a schema and resolve it via a db:// reference pointed at the
	// same container.
	if _, err := pool.Exec(ctx, "CREATE SCHEMA IF NOT EXISTS desired_src"); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _, _ = pool.Exec(context.Background(), "DROP SCHEMA IF EXISTS desired_src CASCADE") })
	if _, err := pool.Exec(ctx, "CREATE TABLE desired_src.t (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, label TEXT)"); err != nil {
		t.Fatal(err)
	}

	cfg := pool.Config().ConnConfig
	dsn := fmt.Sprintf("postgres://keystone_sdk:test@%s:%d/postgres?sslmode=disable&schema=desired_src",
		cfg.Host, cfg.Port)
	ref, err := ParseRef("db://" + dsn)
	if err != nil {
		t.Fatal(err)
	}
	spec, err := ResolveDesired(ctx, ref, nil, "public", schemaspec.Options{SchemaRef: "app"})
	if err != nil {
		t.Fatalf("ResolveDesired(db): %v", err)
	}
	if len(spec.Tables) != 1 || spec.Tables[0].Name != "t" {
		t.Errorf("expected table t, got %+v", spec.Tables)
	}
}

// TestInspectViewUsesPrettyForm locks the inspector to pg_get_viewdef's
// pretty form for regular views (see drift/inspector.go view query).
//
// information_schema.views.view_definition emits the verbose ruleutils
// form — every expression and join fully parenthesised: `sum((a * b))`,
// `((a.id = b.id))`, `(a.k)::text`. pg_get_viewdef(oid, true) strips
// those redundant parens. The differ's normaliseViewBody collapses
// whitespace/case/quotes but does NOT re-parenthesise, so if the
// inspector returns the verbose form it can never equal a pretty-form
// spec.views[].query — the SchemaDefinition re-emits CREATE OR REPLACE
// VIEW every reconcile and never converges to Ready. This test asserts
// the inspector returns the pretty form so that loop cannot regress.
func TestInspectViewUsesPrettyForm(t *testing.T) {
	ctx := context.Background()
	pool := devPool(t)

	const sch = "viewfmt_test"
	mustExec := func(sql string) {
		t.Helper()
		if _, err := pool.Exec(ctx, sql); err != nil {
			t.Fatalf("exec %q: %v", sql, err)
		}
	}
	mustExec("DROP SCHEMA IF EXISTS " + sch + " CASCADE")
	mustExec("CREATE SCHEMA " + sch)
	t.Cleanup(func() { _, _ = pool.Exec(context.Background(), "DROP SCHEMA IF EXISTS "+sch+" CASCADE") })
	mustExec("CREATE TABLE " + sch + ".t1 (id bigint, x bigint, y bigint, k text)")
	mustExec("CREATE TABLE " + sch + ".t2 (id bigint)")
	// A body whose info_schema and pg_get_viewdef renderings differ:
	// arithmetic inside an aggregate, a join predicate, and a cast.
	mustExec("CREATE VIEW " + sch + ".v_demo AS " +
		"SELECT a.id, sum(a.x * a.y) AS s " +
		"FROM " + sch + ".t1 a JOIN " + sch + ".t2 b ON a.id = b.id " +
		"WHERE a.k::text = 'on'::text " +
		"GROUP BY a.id")

	snap, err := drift.NewInspector(pool).Inspect(ctx, sch)
	if err != nil {
		t.Fatalf("Inspect: %v", err)
	}
	var got string
	var found bool
	for _, tbl := range snap.Tables {
		if tbl.Name == "v_demo" {
			got, found = tbl.ViewDefinition, true
			break
		}
	}
	if !found {
		t.Fatalf("v_demo not present in snapshot tables: %+v", snap.Tables)
	}

	var pretty, infoschema string
	if err := pool.QueryRow(ctx,
		"SELECT pg_get_viewdef('"+sch+".v_demo'::regclass, true)").Scan(&pretty); err != nil {
		t.Fatal(err)
	}
	if err := pool.QueryRow(ctx,
		"SELECT view_definition FROM information_schema.views WHERE table_schema=$1 AND table_name='v_demo'",
		sch).Scan(&infoschema); err != nil {
		t.Fatal(err)
	}

	// Sanity: the two PG renderings genuinely differ for this view, so the
	// assertions below are meaningful (verbose parens present in one only).
	if pretty == infoschema {
		t.Fatalf("test view does not exercise the form difference; "+
			"pretty == infoschema:\n%s", pretty)
	}
	if got != pretty {
		t.Errorf("inspector view def is not pg_get_viewdef pretty form\n got: %q\nwant: %q", got, pretty)
	}
	if got == infoschema {
		t.Errorf("inspector still returns the verbose information_schema form (regression)")
	}
}
