// SPDX-License-Identifier: AGPL-3.0-or-later

package analyze

import (
	"context"
	"regexp"
	"strings"

	keystonev1alpha1 "github.com/dogukanturhal/keystone/api/v1alpha1"
)

// Phase 11.3 — 10 more analyzers, bringing the native pack to 20.
// Register these via `DefaultRegistry()` or individually through a
// future `SchemaPolicy.spec.enabledAnalyzers` allowlist.

// -- Rule: no-serial (prefer GENERATED … AS IDENTITY) -------------------

type NoSerial struct{}

func (NoSerial) ID() string { return "no-serial" }
func (NoSerial) Description() string {
	return "SERIAL/BIGSERIAL are legacy; use GENERATED BY DEFAULT AS IDENTITY"
}

var reSerial = regexp.MustCompile(`(?i)\b(SERIAL|BIGSERIAL|SMALLSERIAL)\b`)

func (a *NoSerial) Check(_ context.Context, m *Migration) ([]Finding, error) {
	return statementMatches(m, reSerial, keystonev1alpha1.LintLevelWarning,
		a.ID(),
		"SERIAL/BIGSERIAL/SMALLSERIAL are PostgreSQL pseudo-types backed by "+
			"a sequence + default. Use GENERATED BY DEFAULT AS IDENTITY "+
			"(SQL-standard, cleaner ownership semantics on CREATE/DROP)"), nil
}

// -- Rule: require-timestamptz (no timestamp without time zone) ---------

type RequireTimestamptz struct{}

func (RequireTimestamptz) ID() string { return "require-timestamptz" }
func (RequireTimestamptz) Description() string {
	return "use TIMESTAMPTZ instead of TIMESTAMP (time zone awareness)"
}

// Go's RE2 has no negative lookahead; match all TIMESTAMP occurrences and
// filter post-hoc for the TZ-awareness suffix.
var reTimestampToken = regexp.MustCompile(`(?i)\bTIMESTAMP\b`)
var reTimestampWithTZ = regexp.MustCompile(`(?i)\bTIMESTAMP\s+(?:WITH\s+TIME\s+ZONE|TZ)\b|\bTIMESTAMPTZ\b`)

func (a *RequireTimestamptz) Check(_ context.Context, m *Migration) ([]Finding, error) {
	var out []Finding
	for _, f := range m.Files {
		for i, line := range strings.Split(f.Body, "\n") {
			if !reTimestampToken.MatchString(line) {
				continue
			}
			// Accept lines where the TIMESTAMP is followed by "WITH TIME
			// ZONE" / "TZ" or is actually TIMESTAMPTZ.
			if reTimestampWithTZ.MatchString(line) {
				continue
			}
			out = append(out, Finding{
				Rule:     a.ID(),
				Severity: keystonev1alpha1.LintLevelWarning,
				File:     f.Name,
				Line:     int32(i + 1),
				Message: "TIMESTAMP (without time zone) stores the local clock with no offset. " +
					"Use TIMESTAMPTZ (alias for TIMESTAMP WITH TIME ZONE) unless you " +
					"have a specific reason to store naive local time",
			})
		}
	}
	return out, nil
}

// -- Rule: no-reserved-identifier ---------------------------------------

type NoReservedIdentifier struct{}

func (NoReservedIdentifier) ID() string { return "no-reserved-identifier" }
func (NoReservedIdentifier) Description() string {
	return "avoid SQL reserved words as identifiers (user, order, group, etc.)"
}

// Narrow list — the reserved words most commonly used by accident.
// Full list per pg docs is ~280 entries; this covers the footguns.
var reReservedIdentifier = regexp.MustCompile(`(?i)\b(?:CREATE\s+TABLE|ADD\s+COLUMN|ALTER\s+COLUMN)\s+(user|order|group|type|table|role|schema|index)\b`)

func (a *NoReservedIdentifier) Check(_ context.Context, m *Migration) ([]Finding, error) {
	return statementMatches(m, reReservedIdentifier, keystonev1alpha1.LintLevelWarning,
		a.ID(),
		"reserved SQL keyword used as identifier. Every query referencing this "+
			"object must then quote it, and an unquoted reference parses as the keyword. "+
			"Use a non-reserved synonym (users, orders, groups, etc.)"), nil
}

// -- Rule: max-migration-size (lines per file) --------------------------

type MaxMigrationSize struct {
	// MaxLines caps the acceptable line count per migration file.
	// Default 200 per Keystone convention.
	MaxLines int
}

func (MaxMigrationSize) ID() string { return "max-migration-size" }
func (MaxMigrationSize) Description() string {
	return "large migrations are harder to review and roll back"
}

func (a *MaxMigrationSize) Check(_ context.Context, m *Migration) ([]Finding, error) {
	cap := a.MaxLines
	if cap == 0 {
		cap = 200
	}
	var out []Finding
	for _, f := range m.Files {
		n := strings.Count(f.Body, "\n")
		if n > cap {
			out = append(out, Finding{
				Rule:     a.ID(),
				Severity: keystonev1alpha1.LintLevelNotice,
				File:     f.Name,
				Message: "migration is " + itoa(n) + " lines (> " + itoa(cap) + ") — " +
					"consider splitting into smaller reviewable chunks; " +
					"Keystone's runner already applies each file in its own transaction",
			})
		}
	}
	return out, nil
}

// -- Rule: no-cascade-delete-on-fk --------------------------------------

type NoCascadeDelete struct{}

func (NoCascadeDelete) ID() string { return "no-cascade-delete-on-fk" }
func (NoCascadeDelete) Description() string {
	return "ON DELETE CASCADE silently removes dependent rows"
}

var reCascadeDelete = regexp.MustCompile(`(?i)\bON\s+DELETE\s+CASCADE\b`)

func (a *NoCascadeDelete) Check(_ context.Context, m *Migration) ([]Finding, error) {
	return statementMatches(m, reCascadeDelete, keystonev1alpha1.LintLevelWarning,
		a.ID(),
		"ON DELETE CASCADE silently removes dependent rows on parent delete. "+
			"For regulated data (GDPR/audit trail), prefer ON DELETE RESTRICT + "+
			"explicit application-level cleanup"), nil
}

// -- Rule: require-index-on-fk ------------------------------------------

type RequireIndexOnFK struct{}

func (RequireIndexOnFK) ID() string { return "require-index-on-fk" }
func (RequireIndexOnFK) Description() string {
	return "foreign key columns must have an index (parent delete = full-table scan without)"
}

// Intentionally coarse: flag FOREIGN KEY declarations in files that
// don't also have an INDEX on the same column. Matches the heuristic
// squawk uses.
var reForeignKey = regexp.MustCompile(`(?i)\bFOREIGN\s+KEY\s*\(\s*(\w+)`)
var reIndexOnCol = regexp.MustCompile(`(?i)\bINDEX\b[^;]*\(\s*(\w+)`)

func (a *RequireIndexOnFK) Check(_ context.Context, m *Migration) ([]Finding, error) {
	var out []Finding
	for _, f := range m.Files {
		fkCols := reForeignKey.FindAllStringSubmatch(f.Body, -1)
		if len(fkCols) == 0 {
			continue
		}
		idxCols := make(map[string]bool)
		for _, m := range reIndexOnCol.FindAllStringSubmatch(f.Body, -1) {
			if len(m) > 1 {
				idxCols[strings.ToLower(m[1])] = true
			}
		}
		for _, fk := range fkCols {
			if len(fk) < 2 {
				continue
			}
			col := strings.ToLower(fk[1])
			if !idxCols[col] {
				out = append(out, Finding{
					Rule:     a.ID(),
					Severity: keystonev1alpha1.LintLevelWarning,
					File:     f.Name,
					Message: "FOREIGN KEY on column " + col + " has no detected index. " +
						"Without one, DELETE on the parent table does a full scan of this " +
						"table per parent row. Add CREATE INDEX on the FK column.",
				})
			}
		}
	}
	return out, nil
}

// -- Rule: no-alter-column-set-storage ----------------------------------

type NoAlterColumnSetStorage struct{}

func (NoAlterColumnSetStorage) ID() string { return "no-alter-column-set-storage" }
func (NoAlterColumnSetStorage) Description() string {
	return "ALTER COLUMN SET STORAGE rewrites the table"
}

var reSetStorage = regexp.MustCompile(`(?i)\bALTER\s+COLUMN\s+\w+\s+SET\s+STORAGE\b`)

func (a *NoAlterColumnSetStorage) Check(_ context.Context, m *Migration) ([]Finding, error) {
	return statementMatches(m, reSetStorage, keystonev1alpha1.LintLevelError,
		a.ID(),
		"ALTER COLUMN SET STORAGE rewrites the table and takes AccessExclusive. "+
			"Schedule in maintenance window or avoid."), nil
}

// -- Rule: no-explicit-public-schema ------------------------------------

type NoExplicitPublicSchema struct{}

func (NoExplicitPublicSchema) ID() string { return "no-explicit-public-schema" }
func (NoExplicitPublicSchema) Description() string {
	return "hardcoded 'public' schema prefix breaks multi-tenant rollout"
}

var rePublicSchema = regexp.MustCompile(`(?i)\bpublic\.[a-z_][a-z0-9_]*`)

func (a *NoExplicitPublicSchema) Check(_ context.Context, m *Migration) ([]Finding, error) {
	// Skip when target schema is actually public — that's expected.
	if strings.EqualFold(m.TargetSchema, "public") {
		return nil, nil
	}
	return statementMatches(m, rePublicSchema, keystonev1alpha1.LintLevelWarning,
		a.ID(),
		"hardcoded 'public.table' prefix. Keystone's runner sets "+
			"search_path=<target_schema>, so unqualified names resolve "+
			"per-tenant. Explicit 'public' prefix routes writes to the "+
			"wrong schema in multi-tenant rollouts."), nil
}

// -- Rule: require-migration-comment ------------------------------------

type RequireMigrationComment struct{}

func (RequireMigrationComment) ID() string { return "require-migration-comment" }
func (RequireMigrationComment) Description() string {
	return "first line of migration should be a SQL comment explaining the change"
}

func (a *RequireMigrationComment) Check(_ context.Context, m *Migration) ([]Finding, error) {
	var out []Finding
	for _, f := range m.Files {
		// Walk the first non-blank line; require it start with "--".
		for _, line := range strings.Split(f.Body, "\n") {
			t := strings.TrimSpace(line)
			if t == "" {
				continue
			}
			if !strings.HasPrefix(t, "--") {
				out = append(out, Finding{
					Rule:     a.ID(),
					Severity: keystonev1alpha1.LintLevelNotice,
					File:     f.Name,
					Line:     1,
					Message:  "first non-blank line is not an SQL comment. Add a one-line summary of the migration's intent for future archaeologists.",
				})
			}
			break
		}
	}
	return out, nil
}

// -- Rule: no-alter-table-rename ---------------------------------------

type NoAlterTableRename struct{}

func (NoAlterTableRename) ID() string { return "no-alter-table-rename" }
func (NoAlterTableRename) Description() string {
	return "RENAME TABLE requires apps to coordinate; use a view alias or staged cutover"
}

var reRenameTable = regexp.MustCompile(`(?i)\bALTER\s+TABLE\s+\w+\s+RENAME\s+TO\b`)

func (a *NoAlterTableRename) Check(_ context.Context, m *Migration) ([]Finding, error) {
	return statementMatches(m, reRenameTable, keystonev1alpha1.LintLevelError,
		a.ID(),
		"ALTER TABLE ... RENAME TO is synchronously visible to all connections. "+
			"Apps pointing at the old name error-out. Use a two-phase rollout: "+
			"create a view under the new name, deploy apps, drop the old name"), nil
}

// --- tiny itoa to avoid strconv import in a single-use site ---
func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	var b []byte
	neg := n < 0
	if neg {
		n = -n
	}
	for n > 0 {
		b = append([]byte{byte('0' + n%10)}, b...)
		n /= 10
	}
	if neg {
		return "-" + string(b)
	}
	return string(b)
}
