// SPDX-License-Identifier: Apache-2.0

//! Phase 11.3 extended pack — convention + perf + operational safety.
//! Ported from `rules_extended.go`.

use std::collections::BTreeSet;
use std::sync::LazyLock;

use regex::Regex;

use super::{finding, statement_matches, Analyzer, Finding, LintLevel, Migration};

macro_rules! re {
    ($name:ident, $pat:expr) => {
        static $name: LazyLock<Regex> = LazyLock::new(|| Regex::new($pat).expect($pat));
    };
}

re!(RE_SERIAL, r"(?i)\b(SERIAL|BIGSERIAL|SMALLSERIAL)\b");
re!(RE_TIMESTAMP_TOKEN, r"(?i)\bTIMESTAMP\b");
re!(
    RE_TIMESTAMP_WITH_TZ,
    r"(?i)\bTIMESTAMP\s+(?:WITH\s+TIME\s+ZONE|TZ)\b|\bTIMESTAMPTZ\b"
);
re!(
    RE_RESERVED_IDENTIFIER,
    r"(?i)\b(?:CREATE\s+TABLE|ADD\s+COLUMN|ALTER\s+COLUMN)\s+(user|order|group|type|table|role|schema|index)\b"
);
re!(RE_CASCADE_DELETE, r"(?i)\bON\s+DELETE\s+CASCADE\b");
re!(RE_FOREIGN_KEY, r"(?i)\bFOREIGN\s+KEY\s*\(\s*(\w+)");
re!(RE_INDEX_ON_COL, r"(?i)\bINDEX\b[^;]*\(\s*(\w+)");
re!(
    RE_SET_STORAGE,
    r"(?i)\bALTER\s+COLUMN\s+\w+\s+SET\s+STORAGE\b"
);
re!(RE_PUBLIC_SCHEMA, r"(?i)\bpublic\.[a-z_][a-z0-9_]*");
re!(
    RE_RENAME_TABLE,
    r"(?i)\bALTER\s+TABLE\s+\w+\s+RENAME\s+TO\b"
);

/// no-serial
pub struct NoSerial;
impl Analyzer for NoSerial {
    fn id(&self) -> &'static str {
        "no-serial"
    }
    fn description(&self) -> &'static str {
        "SERIAL/BIGSERIAL are legacy; use GENERATED BY DEFAULT AS IDENTITY"
    }
    fn check(&self, m: &Migration) -> Vec<Finding> {
        statement_matches(
            m,
            &RE_SERIAL,
            LintLevel::Warning,
            self.id(),
            "SERIAL/BIGSERIAL/SMALLSERIAL are PostgreSQL pseudo-types backed by \
             a sequence + default. Use GENERATED BY DEFAULT AS IDENTITY \
             (SQL-standard, cleaner ownership semantics on CREATE/DROP)",
        )
    }
}

/// require-timestamptz
pub struct RequireTimestamptz;
impl Analyzer for RequireTimestamptz {
    fn id(&self) -> &'static str {
        "require-timestamptz"
    }
    fn description(&self) -> &'static str {
        "use TIMESTAMPTZ instead of TIMESTAMP (time zone awareness)"
    }
    fn check(&self, m: &Migration) -> Vec<Finding> {
        let mut out = Vec::new();
        for f in &m.files {
            for (i, line) in f.body.split('\n').enumerate() {
                if !RE_TIMESTAMP_TOKEN.is_match(line) {
                    continue;
                }
                if RE_TIMESTAMP_WITH_TZ.is_match(line) {
                    continue;
                }
                out.push(finding(
                    self.id(),
                    LintLevel::Warning,
                    &f.name,
                    (i + 1) as i32,
                    "TIMESTAMP (without time zone) stores the local clock with no offset. \
                     Use TIMESTAMPTZ (alias for TIMESTAMP WITH TIME ZONE) unless you \
                     have a specific reason to store naive local time",
                ));
            }
        }
        out
    }
}

/// no-reserved-identifier
pub struct NoReservedIdentifier;
impl Analyzer for NoReservedIdentifier {
    fn id(&self) -> &'static str {
        "no-reserved-identifier"
    }
    fn description(&self) -> &'static str {
        "avoid SQL reserved words as identifiers (user, order, group, etc.)"
    }
    fn check(&self, m: &Migration) -> Vec<Finding> {
        statement_matches(
            m,
            &RE_RESERVED_IDENTIFIER,
            LintLevel::Warning,
            self.id(),
            "reserved SQL keyword used as identifier. Every query referencing this \
             object must then quote it, and an unquoted reference parses as the keyword. \
             Use a non-reserved synonym (users, orders, groups, etc.)",
        )
    }
}

/// max-migration-size (default cap 200 newlines)
pub struct MaxMigrationSize;
impl Analyzer for MaxMigrationSize {
    fn id(&self) -> &'static str {
        "max-migration-size"
    }
    fn description(&self) -> &'static str {
        "large migrations are harder to review and roll back"
    }
    fn check(&self, m: &Migration) -> Vec<Finding> {
        const CAP: usize = 200;
        let mut out = Vec::new();
        for f in &m.files {
            let n = f.body.matches('\n').count();
            if n > CAP {
                out.push(finding(
                    self.id(),
                    LintLevel::Notice,
                    &f.name,
                    0,
                    format!(
                        "migration is {n} lines (> {CAP}) — \
                         consider splitting into smaller reviewable chunks; \
                         Keystone's runner already applies each file in its own transaction"
                    ),
                ));
            }
        }
        out
    }
}

/// no-cascade-delete-on-fk
pub struct NoCascadeDelete;
impl Analyzer for NoCascadeDelete {
    fn id(&self) -> &'static str {
        "no-cascade-delete-on-fk"
    }
    fn description(&self) -> &'static str {
        "ON DELETE CASCADE silently removes dependent rows"
    }
    fn check(&self, m: &Migration) -> Vec<Finding> {
        statement_matches(
            m,
            &RE_CASCADE_DELETE,
            LintLevel::Warning,
            self.id(),
            "ON DELETE CASCADE silently removes dependent rows on parent delete. \
             For regulated data (GDPR/audit trail), prefer ON DELETE RESTRICT + \
             explicit application-level cleanup",
        )
    }
}

/// require-index-on-fk
pub struct RequireIndexOnFk;
impl Analyzer for RequireIndexOnFk {
    fn id(&self) -> &'static str {
        "require-index-on-fk"
    }
    fn description(&self) -> &'static str {
        "foreign key columns must have an index (parent delete = full-table scan without)"
    }
    fn check(&self, m: &Migration) -> Vec<Finding> {
        let mut out = Vec::new();
        for f in &m.files {
            let fk_cols: Vec<String> = RE_FOREIGN_KEY
                .captures_iter(&f.body)
                .filter_map(|c| c.get(1).map(|x| x.as_str().to_lowercase()))
                .collect();
            if fk_cols.is_empty() {
                continue;
            }
            let idx_cols: BTreeSet<String> = RE_INDEX_ON_COL
                .captures_iter(&f.body)
                .filter_map(|c| c.get(1).map(|x| x.as_str().to_lowercase()))
                .collect();
            for col in fk_cols {
                if !idx_cols.contains(&col) {
                    out.push(finding(
                        self.id(),
                        LintLevel::Warning,
                        &f.name,
                        0,
                        format!(
                            "FOREIGN KEY on column {col} has no detected index. \
                             Without one, DELETE on the parent table does a full scan of this \
                             table per parent row. Add CREATE INDEX on the FK column."
                        ),
                    ));
                }
            }
        }
        out
    }
}

/// no-alter-column-set-storage
pub struct NoAlterColumnSetStorage;
impl Analyzer for NoAlterColumnSetStorage {
    fn id(&self) -> &'static str {
        "no-alter-column-set-storage"
    }
    fn description(&self) -> &'static str {
        "ALTER COLUMN SET STORAGE rewrites the table"
    }
    fn check(&self, m: &Migration) -> Vec<Finding> {
        statement_matches(
            m,
            &RE_SET_STORAGE,
            LintLevel::Error,
            self.id(),
            "ALTER COLUMN SET STORAGE rewrites the table and takes AccessExclusive. \
             Schedule in maintenance window or avoid.",
        )
    }
}

/// no-explicit-public-schema
pub struct NoExplicitPublicSchema;
impl Analyzer for NoExplicitPublicSchema {
    fn id(&self) -> &'static str {
        "no-explicit-public-schema"
    }
    fn description(&self) -> &'static str {
        "hardcoded 'public' schema prefix breaks multi-tenant rollout"
    }
    fn check(&self, m: &Migration) -> Vec<Finding> {
        // Skip when target schema is actually public — that's expected.
        if m.target_schema.eq_ignore_ascii_case("public") {
            return Vec::new();
        }
        statement_matches(
            m,
            &RE_PUBLIC_SCHEMA,
            LintLevel::Warning,
            self.id(),
            "hardcoded 'public.table' prefix. Keystone's runner sets \
             search_path=<target_schema>, so unqualified names resolve \
             per-tenant. Explicit 'public' prefix routes writes to the \
             wrong schema in multi-tenant rollouts.",
        )
    }
}

/// require-migration-comment
pub struct RequireMigrationComment;
impl Analyzer for RequireMigrationComment {
    fn id(&self) -> &'static str {
        "require-migration-comment"
    }
    fn description(&self) -> &'static str {
        "first line of migration should be a SQL comment explaining the change"
    }
    fn check(&self, m: &Migration) -> Vec<Finding> {
        let mut out = Vec::new();
        for f in &m.files {
            // Walk to the first non-blank line; require it start with "--".
            for line in f.body.split('\n') {
                let t = line.trim();
                if t.is_empty() {
                    continue;
                }
                if !t.starts_with("--") {
                    out.push(finding(
                        self.id(),
                        LintLevel::Notice,
                        &f.name,
                        1,
                        "first non-blank line is not an SQL comment. Add a one-line summary of the migration's intent for future archaeologists.",
                    ));
                }
                break;
            }
        }
        out
    }
}

/// no-alter-table-rename
pub struct NoAlterTableRename;
impl Analyzer for NoAlterTableRename {
    fn id(&self) -> &'static str {
        "no-alter-table-rename"
    }
    fn description(&self) -> &'static str {
        "RENAME TABLE requires apps to coordinate; use a view alias or staged cutover"
    }
    fn check(&self, m: &Migration) -> Vec<Finding> {
        statement_matches(
            m,
            &RE_RENAME_TABLE,
            LintLevel::Error,
            self.id(),
            "ALTER TABLE ... RENAME TO is synchronously visible to all connections. \
             Apps pointing at the old name error-out. Use a two-phase rollout: \
             create a view under the new name, deploy apps, drop the old name",
        )
    }
}

#[cfg(test)]
mod tests {
    use super::super::{FileBody, Migration};
    use super::*;

    fn mig(body: &str) -> Migration {
        Migration {
            files: vec![FileBody {
                name: "001.sql".into(),
                body: body.into(),
            }],
            ..Default::default()
        }
    }

    #[test]
    fn no_serial() {
        assert_eq!(NoSerial.check(&mig("id BIGSERIAL")).len(), 1);
        assert_eq!(NoSerial.check(&mig("id bigint")).len(), 0);
    }

    #[test]
    fn require_timestamptz_filters_tz() {
        assert_eq!(RequireTimestamptz.check(&mig("ts TIMESTAMP")).len(), 1);
        assert_eq!(
            RequireTimestamptz
                .check(&mig("ts TIMESTAMP WITH TIME ZONE"))
                .len(),
            0
        );
        assert_eq!(RequireTimestamptz.check(&mig("ts TIMESTAMPTZ")).len(), 0);
    }

    #[test]
    fn require_index_on_fk() {
        // FK with no index → fires.
        let f = RequireIndexOnFk.check(&mig(
            "CREATE TABLE t (a int, FOREIGN KEY (a) REFERENCES p(id));",
        ));
        assert_eq!(f.len(), 1);
        // FK plus an index on the same col → no finding.
        let f = RequireIndexOnFk.check(&mig(
            "CREATE TABLE t (a int, FOREIGN KEY (a) REFERENCES p(id));\nCREATE INDEX ix ON t (a);",
        ));
        assert_eq!(f.len(), 0);
    }

    #[test]
    fn public_schema_skipped_when_target_public() {
        let mut m = mig("SELECT * FROM public.t;");
        m.target_schema = "tenant_1".into();
        assert_eq!(NoExplicitPublicSchema.check(&m).len(), 1);
        m.target_schema = "public".into();
        assert_eq!(NoExplicitPublicSchema.check(&m).len(), 0);
    }

    #[test]
    fn require_migration_comment() {
        assert_eq!(
            RequireMigrationComment
                .check(&mig("CREATE TABLE t (id int);"))
                .len(),
            1
        );
        assert_eq!(
            RequireMigrationComment
                .check(&mig("-- add t\nCREATE TABLE t (id int);"))
                .len(),
            0
        );
    }

    #[test]
    fn max_migration_size() {
        let big = "x\n".repeat(201);
        assert_eq!(MaxMigrationSize.check(&mig(&big)).len(), 1);
        let small = "x\n".repeat(10);
        assert_eq!(MaxMigrationSize.check(&mig(&small)).len(), 0);
    }
}
