// SPDX-License-Identifier: Apache-2.0

package authoring

import (
	"context"
	"strings"
	"testing"

	keystonev1alpha1 "github.com/dogukanturhal/keystone/api/v1alpha1"
	"github.com/dogukanturhal/keystone-sdk/go/analyze"
	"github.com/dogukanturhal/keystone-sdk/go/declarative"
)

func TestNextVersion(t *testing.T) {
	tests := []struct {
		name     string
		existing []string
		want     string
	}{
		{"empty", nil, "001"},
		{"single", []string{"001_init.up.sql"}, "002"},
		{"gap", []string{"001_a.up.sql", "002_b.up.sql", "005_c.up.sql"}, "006"},
		{"down-files-ignored-dupes", []string{"001_a.up.sql", "001_a.down.sql"}, "002"},
		{"wider-width", []string{"0001_a.up.sql", "0002_b.up.sql"}, "0003"},
		{"non-numeric-skipped", []string{"baseline.up.sql", "002_x.up.sql"}, "003"},
		{"paths", []string{"migrations/007_x.up.sql"}, "008"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := NextVersion(tt.existing); got != tt.want {
				t.Errorf("NextVersion(%v) = %q, want %q", tt.existing, got, tt.want)
			}
		})
	}
}

func TestSanitizeSlug(t *testing.T) {
	tests := map[string]string{
		"add users email index": "add_users_email_index",
		"Add-Users.Email":       "add_users_email",
		"  trim__me  ":          "trim_me",
		"already_ok":            "already_ok",
		"!!!":                   "",
	}
	for in, want := range tests {
		if got := sanitizeSlug(in); got != want {
			t.Errorf("sanitizeSlug(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestRenderUpDown_BasicCreate(t *testing.T) {
	plan := &declarative.Plan{
		Statements: []string{
			"CREATE TABLE widgets (\n    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    name TEXT NOT NULL\n)",
			"CREATE INDEX idx_widgets_name ON widgets (name)",
		},
		ReverseStatements: []string{
			"DROP TABLE IF EXISTS widgets",
			"DROP INDEX CONCURRENTLY IF EXISTS idx_widgets_name",
		},
	}
	b := RenderUpDown(plan, Options{
		Name:        "create widgets",
		Version:     "003",
		Schema:      "app",
		GeneratedBy: "keystonectl test",
	})

	if b.UpFile != "003_create_widgets.up.sql" {
		t.Errorf("UpFile = %q", b.UpFile)
	}
	if b.DownFile != "003_create_widgets.down.sql" {
		t.Errorf("DownFile = %q", b.DownFile)
	}

	// up: leading comment, statement_timeout, then both statements terminated.
	if !strings.HasPrefix(b.Up, "-- create_widgets (up)") {
		t.Errorf("up does not start with a comment header:\n%s", b.Up)
	}
	if !strings.Contains(b.Up, "SET LOCAL statement_timeout = '30s';") {
		t.Errorf("up missing statement_timeout:\n%s", b.Up)
	}
	if !strings.Contains(b.Up, "CREATE TABLE widgets") || !strings.Contains(b.Up, "CREATE INDEX idx_widgets_name ON widgets (name);") {
		t.Errorf("up missing statements:\n%s", b.Up)
	}

	// down: reverse order — index drop FIRST (it was the last forward op),
	// then table drop.
	idxPos := strings.Index(b.Down, "DROP INDEX CONCURRENTLY IF EXISTS idx_widgets_name")
	tblPos := strings.Index(b.Down, "DROP TABLE IF EXISTS widgets")
	if idxPos < 0 || tblPos < 0 {
		t.Fatalf("down missing reverse statements:\n%s", b.Down)
	}
	if idxPos > tblPos {
		t.Errorf("down statements not in reverse order (index should precede table):\n%s", b.Down)
	}
}

func TestRenderUpDown_IrreversiblePerStatement(t *testing.T) {
	plan := &declarative.Plan{
		Statements: []string{
			"ALTER TABLE users ADD COLUMN nickname TEXT",
			"ALTER TABLE users DROP COLUMN legacy_blob",
		},
		ReverseStatements: []string{
			"ALTER TABLE users DROP COLUMN IF EXISTS nickname",
			"", // DROP COLUMN is irreversible (data loss)
		},
	}
	b := RenderUpDown(plan, Options{Name: "tweak_users", Version: "010"})

	if !strings.Contains(b.Down, "-- irreversible: no automatic rollback for: ALTER TABLE users DROP COLUMN legacy_blob") {
		t.Errorf("down missing irreversible marker:\n%s", b.Down)
	}
	if !strings.Contains(b.Down, "ALTER TABLE users DROP COLUMN IF EXISTS nickname;") {
		t.Errorf("down missing reversible statement:\n%s", b.Down)
	}
}

func TestRenderUpDown_FullyIrreversible(t *testing.T) {
	plan := &declarative.Plan{
		Statements:        []string{"ALTER TABLE users DROP COLUMN secret"},
		ReverseStatements: []string{""},
	}
	b := RenderUpDown(plan, Options{Name: "drop_secret", Version: "011"})
	if !strings.Contains(b.Down, "rollback_note") {
		t.Errorf("fully-irreversible down should carry an explicit rollback_note SELECT:\n%s", b.Down)
	}
}

// TestRenderUpDown_LintClean asserts that a generated forward file passes
// the cluster-side analyzer with zero error-severity findings — i.e. the
// renderer produces lint-clean migrations by construction.
func TestRenderUpDown_LintClean(t *testing.T) {
	plan := &declarative.Plan{
		Statements: []string{
			"CREATE TABLE accounts (\n    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    email TEXT NOT NULL,\n    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n)",
			"CREATE INDEX idx_accounts_email_lower ON accounts (LOWER(email))",
		},
		ReverseStatements: []string{
			"DROP TABLE IF EXISTS accounts",
			"DROP INDEX CONCURRENTLY IF EXISTS idx_accounts_email_lower",
		},
	}
	b := RenderUpDown(plan, Options{Name: "create_accounts", Version: "001", Schema: "app", GeneratedBy: "test"})

	m := &analyze.Migration{
		BundleName:   "authoring-test",
		Version:      "001",
		TargetSchema: "app",
		Files:        []analyze.FileBody{{Name: b.UpFile, Body: b.Up}},
	}
	findings, err := analyze.DefaultRegistry().Run(context.Background(), m)
	if err != nil {
		t.Fatalf("analyzer error: %v", err)
	}
	for _, f := range findings {
		if f.Severity == keystonev1alpha1.LintLevelError {
			t.Errorf("generated up.sql has an error-severity finding %q: %s", f.Rule, f.Message)
		}
	}
}

func TestRenderUpDown_StripSchema(t *testing.T) {
	plan := &declarative.Plan{
		Statements: []string{
			`CREATE TABLE "app"."orders" (id bigint, customer_id bigint, FOREIGN KEY (customer_id) REFERENCES "app"."customers" (id))`,
		},
		ReverseStatements: []string{
			`DROP TABLE IF EXISTS "app"."orders"`,
		},
	}
	b := RenderUpDown(plan, Options{Name: "create_orders", Version: "002", Schema: "app", StripSchema: "app"})
	if strings.Contains(b.Up, `"app".`) {
		t.Errorf("up still contains schema qualifier after StripSchema:\n%s", b.Up)
	}
	if !strings.Contains(b.Up, `CREATE TABLE "orders"`) {
		t.Errorf("up missing schema-relative table:\n%s", b.Up)
	}
	if !strings.Contains(b.Up, `REFERENCES "customers"`) {
		t.Errorf("up FK not made schema-relative:\n%s", b.Up)
	}
	if strings.Contains(b.Down, `"app".`) {
		t.Errorf("down still contains schema qualifier:\n%s", b.Down)
	}
}

func TestRenderUpDown_NilPlan(t *testing.T) {
	b := RenderUpDown(nil, Options{Name: "noop", Version: "001"})
	if !strings.Contains(b.Up, "SET LOCAL statement_timeout") {
		t.Errorf("nil plan up should still have a header:\n%s", b.Up)
	}
	if !strings.Contains(b.Down, "rollback_note") {
		t.Errorf("nil plan down should carry the rollback_note:\n%s", b.Down)
	}
	files := b.Files()
	if len(files) != 2 {
		t.Errorf("Files() returned %d entries, want 2", len(files))
	}
}
