-- Identity variants, STORED generated columns, and type modifiers.
-- Regression: identity was dropped to a bare sequence; typmods
-- (varchar(n), numeric(p,s)) were lost; STORED expressions vanished.
CREATE TABLE line_items (
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    sku         varchar(64) NOT NULL,
    description varchar(255),
    qty         integer NOT NULL DEFAULT 1,
    unit_price  numeric(12,2) NOT NULL,
    total       numeric(12,2) GENERATED ALWAYS AS (qty * unit_price) STORED,
    ratio       double precision,
    note        char(8)
);

CREATE TABLE counters (
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text NOT NULL
);
