-- ORM-shaped schema: quoted mixed-case identifiers, explicitly named
-- constraints, identity primary keys, and a foreign key that can only
-- reference a UNIQUE *constraint* (not a bare unique index).
-- Regression: primary keys vanished from quoted-identifier schemas, and
-- UNIQUE constraints were demoted to indexes.
CREATE TABLE "Tenants" (
    "Id"        integer GENERATED ALWAYS AS IDENTITY,
    "Slug"      text NOT NULL,
    "Code"      text,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_Tenants"      PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_Tenants_Slug" UNIQUE ("Slug"),
    CONSTRAINT "UQ_Tenants_Code" UNIQUE NULLS NOT DISTINCT ("Code")
);

CREATE TABLE "Users" (
    "Id"         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantSlug" text NOT NULL,
    "Email"      text NOT NULL,
    CONSTRAINT "FK_Users_Tenants" FOREIGN KEY ("TenantSlug")
        REFERENCES "Tenants" ("Slug") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
